### ISSUE TITLE
Xubuntu 22.04 "No suitable display mode"

### ISSUE THREAD

**Issue by LinuxforPunks** [axle-h/baby-smash#4]
I get this error on running the application:-

dave@ubuntustudio2019:~/babysmash/baby-smash/build$ ./baby-smash
[2023-01-19 21:09:11.151] [logger] [critical] No suitable display mode

(also)
In the readme.md instructions, relative filepaths are quoted absolutely, e.g. "To run:  Ubuntu ./baby-smash"

But this command will only work if the user is in the same directory as the application (in which case the instructions need to remind them to navigate there). imo an _installed_ application should run from any location which I think is done by adding a symlink into usr/bin but I'm not a developer

**Comment by axle-h** [comment]
Hi, not sure what your issue is, you are running this from the desktop aren't you? Not from wsl or something? And not on some really oddball resolution?
Baby smash delegates choosing a display mode to SDL2, which picks the closest to what's configured. Maybe drop the resolution? See the readme for the location of the config file. Maybe also try disabling full screen to test.
Thanks for reporting that broken command, it is intended to work (it isn't absolute btw), I updated the build to run from the repo root but missed that line. BTW there's an (out of date) .deb package which, assuming xubuntu desktop works like Ubuntu, you could install and then you get a menu icon to click. Watch out for a new build.

**Comment by klachoo** [comment]
@evild4ve @axle-h
I have managed to reproduce the very same issue on Linux Mint 21 with Cinnamon desktop environment.
The issue is that for some reason the default version of the configuration file available at `~/.local/share/[username]/baby-smash/config.json` uses an invalid value for `internalResolution`.
The default content of the config file for me is as follows:
`{
    "render": {
        "debugPhysics": false,
        "fullScreen": true,
        "internalResolution": {
            "height": 1080,
            "width": 1920
        },
        "pixelsPerMeter": 20.0
    },
    "sandbox": {
        "enabled": true
    },
    "world": {
        "gravity": -1.0
    }
}
`
There existis however a workaround.
First of all please do edit the above mentioned configuration file and set `fullScreen` to `false`. Then run the game and it should start OK in windowed mode (disregarding the 'wrong' resolution).
Then do run the following command in the terminal, which will list all available display modes (ie. resolutions) for your system: `xrandr -d :0`. A sample output generated for me is as follows:
`Screen 0: minimum 8 x 8, current 1600 x 900, maximum 16384 x 16384
eDP-1-1 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 382mm x 215mm
   1600x900      60.08*+  60.08  
   1400x900      60.08  
   1440x810      60.08  
   1368x768      60.08  
   1280x800      60.08  
   1280x720      60.08  
   1024x768      60.08  
   960x720       60.08  
   928x696       60.08  
   896x672       60.08  
   1024x576      60.08  
   960x600       60.08  
   960x540       60.08  
   800x600       60.08  
   840x525       60.08  
   864x486       60.08  
   700x525       60.08  
   800x450       60.08  
   640x512       60.08  
   700x450       60.08  
   640x480       60.08  
   720x405       60.08  
   684x384       60.08  
   640x360       60.08  
   512x384       60.08  
   512x288       60.08  
   480x270       60.08  
   400x300       60.08  
   432x243       60.08  
   320x240       60.08  
   360x202       60.08  
   320x180       60.08  
VGA-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
`
The final step is to re-enable full screen mode, set one of the above detected resolutions in the config file and start the game again. Following works fine for me with the game starting correctly in full screen mode:
`
        "fullScreen": true,
        "internalResolution": {
            "height": 900,
            "width": 1600
        },
`
Hope this is of help :smile:.
