### ISSUE TITLE
cool project and I have some hints for disable control keys

### ISSUE THREAD

**Issue by tsingakbar** [axle-h/baby-smash#5]
This is not an issue.
Just googled keyboard smashing games and came across this, and my 4 year old nephew is quite happy with this, thank you for your game!

I'm a linux user, and the only trouble is how to eliminate the input method and desktop manager's shortcut to avoid switch the game to background. Tried `run_toddler_sandbox` but we are out of luck because introduced new trouble of setting up root user's xorg display, and finally wrote a small script to achieve the goal without requirement of root user:
```bash
#!/usr/bin/env bash
# disable input method for the game process, which is required for CJK people.
unset GTK_IM_MODULE
unset QT_IM_MODULE
unset XMODIFIERS
# make pressing windows start key(aka. xorg's Super_L) useless, and as a KDE user this is enough to make KDE quiet
# better use xev to test your keyboard's windows start key's keycode, while most keyboard is 133
xmodmap -e 'keycode 133=NoSymbol'
./target/release/keyboard-zoo
# restore the windows start key's functionality
xmodmap -e 'keycode 133=Super_L'

```

**Comment by axle-h** [comment]
Thanks for the message, glad to see at least one other person is enjoying this project!
Yeah the sandbox is not great it's using some obscure crate: [rdev](https://docs.rs/rdev/latest/rdev/). This has been good enough for me on my platforms: macos + Windows.
There's definitely a better way to do it and Linux is a massive pain due to X11+Wayland. Your script would not work on Wayland for eg.
Someone needs to write a rust crate that merges all the different low level input APIs on all the platforms. Then this project will be complete!
